Moved info printing -- now progressive

diff --git a/shk-linux-conf b/shk-linux-conf
--- a/shk-linux-conf
+++ b/shk-linux-conf
@@ -41,7 +41,6 @@ for argv in $@ ; do
 	"--") shift && break ;;
     esac
 done
-echo "$github_user@github:$github_repo/$repo_branch"
 
 [ -z "$github_user" ] || [ -z "$github_repo" ] || [ -z "$repo_branch" ] && usage
 
@@ -123,95 +122,97 @@ function get_remote_infos() {
 
 function list() {
     local uri="$1"
+    local brief="$2"
     [ -z "$uri" ] && return
     while read line ; do
         if [ -n "$(echo $line | egrep "/$github_user/$github_repo/blob/[0-9a-f]+/\S+")" ] ; then
 	    file=$(echo "$line" | sed -r "s#^.+/$github_user/$github_repo/blob/[0-9a-f]+/(\S+)\".+\$#\1#")
-	    printf "."
 	    get_remote_infos "$file"
 	    if [ $? -eq 1 ] ; then
 	        get_local_infos "${remote_realpaths_array[$index - 1]}"
+                if [ -n "$brief" ] ; then
+                    show_brief_infos $(($index - 1))
+                else
+                    show_infos $(($index - 1))
+                fi
 	    fi
         elif [ -n "$(echo $line | egrep "/$github_user/$github_repo/tree/[0-9a-f]+/\S+")" ] ; then
 	    dir=$(echo "$line" | sed -r "s#^.+/$github_user/$github_repo/tree/[0-9a-f]+/(\S+)\".+\$#\1#")
-            printf "."
-            list "/tree/$repo_branch/$dir"
+            list "/tree/$repo_branch/$dir" "$brief"
         fi
     done < <(curl -s "https://github.com/$github_user/$github_repo$uri" | grep "href=" | grep -v "rel='permalink'" | grep -v "Breadcrumb")
 }
 
-CMD="$1"
-case $CMD in
+function show_brief_infos() {
+    local i=$1
+    printf "[${remote_files_array[$i]}] ${remote_paths_array[$i]}\n"
+}
+
+function show_infos() {
+    local i=$1
+    printf "[${remote_files_array[$i]}] ${remote_paths_array[$i]} <local r${local_tags_array[$i]} | r${remote_tags_array[$i]} remote> -- "
+    if [ ${local_tags_array[$i]} -eq 0 ] ; then
+	printf "file not found\n"
+	if [ $force = "true" ] ; then
+            if [ $cmd = "--check" ] ; then
+                printf "  [force] will download\n"
+            elif [ $cmd = "--update" ] ; then
+                get_file "force" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
+            fi
+        fi
+    elif [ ${local_tags_array[$i]} -eq ${remote_tags_array[$i]} ] ; then
+	printf "up to date\n"
+    elif [ ${local_tags_array[$i]} -lt ${remote_tags_array[$i]} ] ; then
+	printf "update available\n"
+        if [ $cmd = "--check" ] ; then
+	    printf "  will update\n"
+        elif [ $cmd = "--update" ] ; then
+	    get_file "" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
+        fi
+    else
+	printf "something is wrong\n"
+	if [ $force = "true" ] ; then
+            if [ $cmd = "--check" ] ; then
+                printf "  [force] will download\n"
+            elif [ $cmd = "--update" ] ; then
+                get_file "force" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
+            fi
+        fi
+    fi
+}
+
+cmd="$1"
+shift
+case $cmd in
     "--list")
-        [ $# -ne 1 ] && usage
-	i=0
-	list "/"
-        printf "\n"
-	while [ $i -lt $index ] ; do
-	    echo "[${remote_files_array[$i]}] ${remote_paths_array[$i]} r${remote_tags_array[$i]}"
-	    i=$(($i + 1))
-	done
+        [ $# -ne 0 ] && usage
+	list "/" "--brief"
 	;;
     "--check"|"--update")
-	shift
 	if [ $# -eq 0 ] ; then
 	    list "/"
-            printf "\n"
 	else
 	    for file in $@ ; do
 		get_remote_infos "$file"
 		if [ $? -eq 1 ] ; then
 		    get_local_infos "${remote_realpaths_array[$index - 1]}"
+                    show_infos $(($index - 1))
 		else
 		    errors=$(($errors + 1))
 		    echo "$file: no such remote file" >&2
 		fi
 	    done
 	fi
-	i=0
-	while [ $i -lt $index ] ; do
-	    echo -n "[${remote_files_array[$i]}] ${remote_paths_array[$i]} local(r${local_tags_array[$i]}) remote(r${remote_tags_array[$i]}) -- "
-	    if [ ${local_tags_array[$i]} -eq 0 ] ; then
-		echo "file not found"
-		if [ $force = "true" ] ; then
-                    if [ $CMD = "--check" ] ; then
-                        echo "  [force] will download"
-                    elif [ $CMD = "--update" ] ; then
-                        get_file "force" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
-                    fi
-                fi
-	    elif [ ${local_tags_array[$i]} -eq ${remote_tags_array[$i]} ] ; then
-		echo "up to date"
-	    elif [ ${local_tags_array[$i]} -lt ${remote_tags_array[$i]} ] ; then
-		echo "update available"
-                if [ $CMD = "--check" ] ; then
-		    echo "  will update"
-                elif [ $CMD = "--update" ] ; then
-		    get_file "" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
-                fi
-	    else
-		echo "something is wrong"
-		if [ $force = "true" ] ; then
-                    if [ $CMD = "--check" ] ; then
-                        echo "  [force] will download"
-                    elif [ $CMD = "--update" ] ; then
-                        get_file "force" "${remote_url_array[$i]}" "${remote_realpaths_array[$i]}"
-                    fi
-                fi
-	    fi
-	    i=$(($i + 1))
-	done
 	;;
     "--help")
 	usage
 	;;
     *)
-	echo "$CMD: unknown command" >&2
+	echo "shk-linux-conf: $cmd: unknown command" >&2
 	usage
 	;;
 esac
 
-echo -n "$index remote files parsed, $downloads downloaded ($errors errors)"
-[ $force = "true" ] && echo " [force]" || echo ""
+printf "$index remote files parsed, $downloads downloaded ($errors errors)\n"
 
 # EOF
